### ISSUE TITLE
It takes a very long time to load participants

### ISSUE THREAD

**Issue by JeffreyCA** [robrua/Orianna#22]
When I use 
```
List<Participant> myList = currentgame.getParticipants();
   for (int i = 0; i < myList.size(); i++) {
   Log.i(String.valueOf(i), myList.get(i).toString());
}
```

it takes 5-10 seconds to load all of the participants, which is a really long time. Is there a faster way to do it? I have tried using `RiotAPI.setLoadPolicy(LoadPolicy.LAZY);`.

**Comment by robrua** [comment]
So this is actually a really strange situation. Your problem here is because of two things:

1) The participant toString() method tells you the participant's champion and
2) You're using the LAZY load policy.

Since you're set to LAZY, if you haven't grabbed the entire Champion list at some point and cached it, Orianna goes to grab each champion individually by ID when you call that participant's toString(). This will take up to 10 calls, so you'll likely run up against your rate limit.

Existing solutions are:
1) Call RiotAPI.getChampions() at some point before this so all the champions get cached
2) Switch to the UPFRONT load policy

I also may switch the toString() on participant to not load the champion with LAZY unless it's already cached, but for now either of the above two should solve your problem.

**Comment by JeffreyCA** [comment]
Ok thanks, I'll just use UPFRONT. I think the requests are slow because of Riot's API servers. They are often down or not working.

**Comment by robrua** [comment]
Yeah, the servers have been a bit unstable the past couple of days. I think it should be back to normal soon.
