### ISSUE TITLE
Tier issue

### ISSUE THREAD

**Issue by LeoStoch** [robrua/Orianna#29]
Hey, I think I found a new Issue:
CurrentGame Game = RiotAPI.getCurrentGame(message[1]);
				for(Participant g: Game.getParticipants()){
					Summoner summ = RiotAPI.getSummonerByName(g.getSummonerName());
					Tier tier = Tier.UNRANKED;
					try{
					for(League leag: RiotAPI.getLeaguesBySummoner(g.getSummoner())){
						tier = leag.getTier();
					}}catch(Exception e){
						tier = Tier.UNRANKED;
					}
System.out.println(tier);
Some player gets a wrong output (like a plat player get as output "BRONZE" or a ranked player gets unranked) I think thats an issue with the API but I am nor sure. (tried it manually with the riotapi and got the right tier)

**Comment by robrua** [comment]
Hey. I think you might want to double check your logic on this code. It looks like you're trying to find the highest tier that the player has achieved this season over all ranked queues. The reason you're not getting the output you expect is that you set the value of tier for EACH league that the summoner is in (overwriting the previous value), so the output will just be the tier of the last league the API sent, rather than the highest tier they've achieved. Instead, you should compare leag.getTier() to the existing value of tier on each iteration and only replace the value if it's higher than the current value of tier.

As some side notes, you'll probably want to look into these functions to make your code simpler/more efficient:

Participant.getSummoner()

Summoner.getLeagueEntries()     
(LeagueEntries loads data for just the summoner in question, rather than the entire league. It'll use fewer API calls.)

**Comment by LeoStoch** [comment]
I want to get the current league of the players that the person is playing with and if I use Summoner.getLeagueEntries() I got the same problam, it gives me not for every person the correct tier.

**Comment by robrua** [comment]
Regardless of if you're using leagueEntries or leagues, you still need to make sure you're not just overwriting your tier variable for each league's tier. This will result in always returning the tier for the last league Riot sent, rather than solo queue. If you want the solo queue tier, you need to make sure you're setting your tier variable to the tier for the solo queue league, and no other.

**Comment by LeoStoch** [comment]
If they are only ranked in solo queue should I get only 1 (the soloq) tier, or not?

**Comment by robrua** [comment]
Yeah - you'll only get solo queue if the player isn't ranked on any team.

**Comment by LeoStoch** [comment]
Because sometime I got no/a wrong tier (from players that are not ranked in any tem)

**Comment by robrua** [comment]
Can you provide me a specific player for whom you're seeing that problem, or some way to reproduce it?

The API doesn't offer any play-by-play information for live games.

**Comment by LeoStoch** [comment]
found no example player right now, but found something else. EUW: Schnua is in SoloQ gold and with his 3v3 team silver, but I got an exception(so he got UNRANKED with catch)

**Comment by robrua** [comment]
I can't reproduce this problem - it works just fine for me. The following code:
```java
Summoner s = RiotAPI.getSummonerByName("Schnua");
for(League l : s.getLeagueEntries()) {
    System.out.println(l.getQueueType() + " - " + l.getTier());
}
```
Results in:
```
RANKED_SOLO_5x5 - GOLD
RANKED_TEAM_3x3 - SILVER
```

**Comment by LeoStoch** [comment]
Kay, so I think it was my fail sorry^^

**Comment by robrua** [comment]
No problem
