### ISSUE TITLE
AsyncRiotAPI.getCurrentGame() returns null

### ISSUE THREAD

**Issue by Coppercrawler** [robrua/Orianna#8]
AsyncRiotAPI.getCurrentGame() returns null and so handle() is never called

**Comment by robrua** [comment]
Right now, handle for currentGame() should be used to handle other API Exceptions besides 404s. Returning null when there is no current game is special behavior for this endpoint which was suggested due to the frequency of 404s from the endpoint. You should check if the game returned in perform() is null instead.

**Comment by Coppercrawler** [comment]
Okay, thanks.
